production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  max_retries_on_connection_failure: 20
  persist_in_safe_mode: true
  skip_version_check: true
development:
  sessions:
    default:
      database: sprtid
      hosts:
        - localhost:27017
  database: sprtid
sprtid:
  sessions:
    default:
      database: sprtid
      hosts:
        - localhost:27017
